#!/bin/sh

SERVICES_IN_JOURNAL_PARAM=
for SERVICE in $(all-zenux-services); do
    SERVICES_IN_JOURNAL_PARAM="${SERVICES_IN_JOURNAL_PARAM} UNIT=${SERVICE}.service + _SYSTEMD_UNIT=${SERVICE}.service +"
done

journalctl $@ -b -o short-monotonic \
    ${SERVICES_IN_JOURNAL_PARAM} \
    SYSLOG_IDENTIFIER=vf-declarative-gui + \
    SYSLOG_IDENTIFIER=zera-usb-automount.sh + \
    _COMM=cat
